name: Bump Version and Publish

permissions:
  contents: write  # дает права на запись в репозиторий

on:
  push:
    branches:
      - main  # Этот workflow будет срабатывать, когда что-то будет пушиться в main

jobs:
  bump_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Poetry
        run: pip install poetry

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Bump version
        run: |
          poetry version patch  # Поднимай версию

          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

          git add pyproject.toml
          git commit -m "chore: bump version"

          # Создаём новую ветку для пуша
          git checkout -b bump-version-branch

          # Пушим изменения в новую ветку
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/RoFhdsa/AstFriend.git HEAD:bump-version-branch

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # токен для взаимодействия с репозиторием
          title: "Bump Version"  # Заголовок PR
          body: "This PR bumps the version automatically."  # Описание PR
          base: main  # Основная ветка, куда будет сделан PR
          head: bump-version-branch  # Ветка с изменениями
          draft: false  # Убираем статус черновика, чтобы PR был готов к слиянию